---
title: "tpe-vignette"
author: "Florian Larue"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tpe-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=TRUE}
library(CGMTPE)
library(ggplot2)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r}
# load example data
loadData()
param[2,] <- param[1,] #TODO; remove, tmp testing
# create a TPE analysis object
TPE_analysis <- createTpe(varieties=c("Fadda","Grinkan"),
                 environments=c("BAMA2014S1"),
                 parameters=param)

# set weather data and observation data from the data loaded with loadData()
TPE_analysis$set_weather(weather)
TPE_analysis$set_obs(varID=1, obs)

# run parameter estimation, will also update the parameters of the TPE a object
TPE_analysis$runEstimation(varID=c(1,2), maxiter=5, paramnames=paramOfInterest)

# create a simulation grid
TPE_analysis$createGrid("grid1", 0.5, 39, 22, -16.59, 9.20)

# generate climate on each point of the grid
TPE_analysis$genClimate(gridID=1, year=2014, yearNb=1, path="D:\\Marksim\\",
                        filesE=T)

# run model simulation on each point of the grid using estimated parameters
TPE_analysis$runGridSim(gridID=1, varID=1, trait="GrainYieldPopFin",
                        year=2014, soilData=soil, latlonData=lat_lon)

# create a map of the studied region in TPE anaylisis
TPE_analysis$createMap(res=150, bounds=c(17,5,5,-20))

# plot map
TPE_analysis$plotMap()
print(TPE_analysis$grids[[1]]$plots[[1]])

```
